### ISSUE TITLE
Error applying patch onto gstreamer1.0-plugins-bad-1.24.12-r0

### ISSUE THREAD

**Issue by jpetrina** [JeffyCN/meta-rockchip#167]
Hi maintainers,

I'm getting the following error when building on `walnascar`:

```
builder@0214696177e3:/work/.../gst-plugins-bad-1.24.12$ quilt push -f 
Applying patch patches/0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch 
patching file ext/gtk/gstgtkwaylandsink.c 
patching file ext/wayland/gstwaylandsink.c 
patching file gst-libs/gst/wayland/gstwldisplay.c 
Hunk #3 FAILED at 205. 
Hunk #5 succeeded at 220 with fuzz 2. 
Hunk #6 succeeded at 238 (offset 1 line). 
Hunk #7 succeeded at 279 (offset 1 line). 
1 out of 7 hunks FAILED -- saving rejects to file gst-libs/gst/wayland/gstwldisplay.c.rej 
patching file gst-libs/gst/wayland/gstwldisplay.h 
patching file gst-libs/gst/wayland/gstwllinuxdmabuf.c 
patching file gst-libs/gst/wayland/gstwlvideobufferpool.c 
patching file gst-libs/gst/wayland/gstwlvideoformat.c 
patching file gst-libs/gst/wayland/gstwlvideoformat.h 
patching file gst-libs/gst/wayland/gstwlwindow.c 
patching file gst-libs/gst/wayland/gstwlwindow.h 
Applied patch patches/0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch (forced; needs refresh) 

 builder@0214696177e3:/work/.../gst-plugins-bad-1.24.12$ cat gst-libs/gst/wayland/gstwldisplay.c.rej 
--- gst-libs/gst/wayland/gstwldisplay.c 
+++ gst-libs/gst/wayland/gstwldisplay.c 
@@ -205,6 +206,8 @@ dmabuf_modifier (void *data, struct zwp_linux_dmabuf_v1 *zwp_linux_dmabuf, 
{ 
   GstWlDisplay *self = data; 
   guint64 modifier = (guint64) modifier_hi << 32 | modifier_lo; 
+ 
+#if 0 // HACK: Allow all formats 
   static gboolean table_header = TRUE; 
 
   GstWlDisplayPrivate *priv = gst_wl_display_get_instance_private (self); 
```

From the online [GStreamer v1.24.12 source](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.24.12/subprojects/gst-plugins-bad/gst-libs/gst/wayland/gstwldisplay.c?ref_type=tags#L202) there doesn't seem to be `table_header` line:

```c
static void
dmabuf_modifier (void *data, struct zwp_linux_dmabuf_v1 *zwp_linux_dmabuf,
    uint32_t format, uint32_t modifier_hi, uint32_t modifier_lo)
{
  GstWlDisplay *self = data;
  guint64 modifier = (guint64) modifier_hi << 32 | modifier_lo;
  static uint32_t last_format = 0;

...
```

but [GStreamer v1.24.11 does have it](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.24.11/subprojects/gst-plugins-bad/gst-libs/gst/wayland/gstwldisplay.c?ref_type=tags#L202):

```c
static void
dmabuf_modifier (void *data, struct zwp_linux_dmabuf_v1 *zwp_linux_dmabuf,
    uint32_t format, uint32_t modifier_hi, uint32_t modifier_lo)
{
  GstWlDisplay *self = data;
  guint64 modifier = (guint64) modifier_hi << 32 | modifier_lo;
  static gboolean table_header = TRUE;

```

The `gstreamer1.0-plugins-bad_1.24.12` patchdir seems to be a symlink to `gstreamer1.0-plugins-bad_1.24.11` but maybe it should be rebased?

Let me know if I'm missing something, thanks!

---

**edit**: after manually refreshing the particular patch I get the following:

```
| ../gst-plugins-bad-1.24.12/gst-libs/gst/wayland/gstwllinuxdmabuf.c: In function 'gst_wl_linux_dmabuf_construct_wl_buffer':
| ../gst-plugins-bad-1.24.12/gst-libs/gst/wayland/gstwllinuxdmabuf.c:74:11: error: passing argument 2 of 'gst_wl_display_check_format_for_dmabuf' makes integer from pointer without a cast [-Wint-conversion]
|    74 |           drm_info), NULL);
|       |           ^~~~~~~~
|       |           |
|       |           const GstVideoInfoDmaDrm * {aka const struct _GstVideoInfoDmaDrm *}
```

**Comment by jpetrina** [comment]
Even when trying to compile on `v1.24.11` I get the similar error so I'll take a look what the issue is:

```
| In file included from /work/build/tmp/work/cortexa72-cortexa53-crypto-oe-linux/gstreamer1.0-plugins-bad/1.24.11/recipe-sysroot/usr/lib/glib-2.0/include/glibconfig.h:9,
|                  from /work/build/tmp/work/cortexa72-cortexa53-crypto-oe-linux/gstreamer1.0-plugins-bad/1.24.11/recipe-sysroot/usr/include/glib-2.0/glib/gtypes.h:34,
|                  from /work/build/tmp/work/cortexa72-cortexa53-crypto-oe-linux/gstreamer1.0-plugins-bad/1.24.11/recipe-sysroot/usr/include/glib-2.0/glib/galloca.h:34,
|                  from /work/build/tmp/work/cortexa72-cortexa53-crypto-oe-linux/gstreamer1.0-plugins-bad/1.24.11/recipe-sysroot/usr/include/glib-2.0/glib.h:32,
|                  from /work/build/tmp/work/cortexa72-cortexa53-crypto-oe-linux/gstreamer1.0-plugins-bad/1.24.11/recipe-sysroot/usr/include/gstreamer-1.0/gst/gst.h:27,
|                  from ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/wayland-prelude.h:23,
|                  from ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/wayland.h:30,
|                  from ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/gstwllinuxdmabuf.h:25,
|                  from ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/gstwllinuxdmabuf.c:29:
| ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/gstwllinuxdmabuf.c: In function 'gst_wl_linux_dmabuf_construct_wl_buffer':
| ../gst-plugins-bad-1.24.11/gst-libs/gst/wayland/gstwllinuxdmabuf.c:74:11: error: passing argument 2 of 'gst_wl_display_check_format_for_dmabuf' makes integer from pointer without a cast [-Wint-conversion]
|    74 |           drm_info), NULL);
|       |           ^~~~~~~~
|       |           |
|       |           const GstVideoInfoDmaDrm * {aka const struct _GstVideoInfoDmaDrm *}
```

---

edit: so the [0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch](https://github.com/JeffyCN/meta-rockchip/blob/5a9e7685b1245fff24a2070898c84c1e73afa09f/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.24.11/0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch) does this:

```diff
diff --git a/gst-libs/gst/wayland/gstwldisplay.h b/gst-libs/gst/wayland/gstwldisplay.h
index 3d29b4ea..a7f8c8d7 100644
--- a/gst-libs/gst/wayland/gstwldisplay.h
+++ b/gst-libs/gst/wayland/gstwldisplay.h
@@ -68,7 +68,7 @@ gboolean gst_wl_display_check_format_for_shm (GstWlDisplay * self,
 
 GST_WL_API
 gboolean gst_wl_display_check_format_for_dmabuf (GstWlDisplay * self,
-    const GstVideoInfoDmaDrm *drm_info);
+    const guint fourcc, const guint64 modifier);
```

but it doesn't update the [gst-libs/gst/wayland/gstwllinuxdmabuf.c](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.24.11/subprojects/gst-plugins-bad/gst-libs/gst/wayland/gstwllinuxdmabuf.c?ref_type=tags#L101) usage:

```c
  g_return_val_if_fail (gst_wl_display_check_format_for_dmabuf (display,
          drm_info), NULL);
```

---

edit: fixed by updating the patchfile:

```
builder@65438920ac74:/work/build$ cd $(bitbake-getvar -r gstreamer1.0-plugins-bad S --value)

builder@65438920ac74:.../gst-plugins-bad-1.24.11$ quilt pop 0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch
(...)
Removing patch 0021-waylandsink-Prefer-to-use-waylandsink.patch
Restoring ext/wayland/gstwaylandsink.c

Now at patch 0020-waylandsink-Support-NV12_10LE40-NV16_10LE40-and-NV12.patch
```

fix file `gst-libs/gst/wayland/gstwllinuxdmabuf.c`, and then

```
builder@65438920ac74:.../gst-plugins-bad-1.24.11$ quilt refresh -p ab --no-timestamps --no-index
```

Now the gstreamer package compiles sucessfully.

**Comment by tickmoo** [comment]
详细的修复补丁可以发一下吗？非常感谢！

**Comment by JeffyCN** [comment]
Should be fixed, thanks
